version: '3.9'
services:
  # Use domestic mirrors for faster pulls in mainland China
  postgres:
    image: docker.m.daocloud.io/library/postgres:16

  redis:
    image: docker.m.daocloud.io/library/redis:7-alpine

  minio:
    image: docker.m.daocloud.io/minio/minio:RELEASE.2024-08-17T01-24-54Z

  zookeeper:
    image: docker.m.daocloud.io/confluentinc/cp-zookeeper:7.6.1

  kafka:
    image: docker.m.daocloud.io/confluentinc/cp-kafka:7.6.1

  kafka-ui:
    image: docker.m.daocloud.io/provectuslabs/kafka-ui:v0.7.2

  nginx:
    image: docker.m.daocloud.io/library/nginx:1.27-alpine

  api-gateway:
    build:
      args:
        NODE_IMAGE: docker.m.daocloud.io/library/node:20-alpine

  user-service:
    build:
      args:
        NODE_IMAGE: docker.m.daocloud.io/library/node:20-alpine

  school-integration:
    build:
      args:
        NODE_IMAGE: docker.m.daocloud.io/library/node:20-alpine

  regulator-service:
    build:
      args:
        NODE_IMAGE: docker.m.daocloud.io/library/node:20-alpine
