-- Align hygiene tables to BIGINT UNSIGNED auto-increment ids

ALTER TABLE hygiene_inspections
  MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  MODIFY COLUMN school_id BIGINT UNSIGNED NOT NULL,
  MODIFY COLUMN date DATETIME NOT NULL;

ALTER TABLE asset_maintenance
  MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  MODIFY COLUMN school_id BIGINT UNSIGNED NOT NULL,
  MODIFY COLUMN date DATETIME NOT NULL;
