import { Injectable, MessageEvent, BadRequestException } from '@nestjs/common';
import { Observable, Subject } from 'rxjs';
import { HygieneRepository } from './repositories/hygiene.repository';

export type InspectResult = '合格' | '不合格';

export type HygieneInspection = {
  id: number;
  schoolId: number;
  date: string; // ISO date/time
  result: InspectResult;
  by: string; // 检查人
  remark?: string;
};

export type AssetMaintenance = {
  id: number;
  schoolId: number;
  asset: string;
  date: string; // ISO date/time
  action: string; // 维护内容
  by: string; // 负责人
};

@Injectable()
export class HygieneService {
  private seqI = 1;
  private seqA = 1;
  private events$ = new Subject<MessageEvent>();

  constructor(private readonly repo: HygieneRepository) {}

  // ids are generated by DB auto-increment
  private nowIso() {
    return new Date().toISOString();
  }
  private emit(type: string, data: any) {
    this.events$.next({ type, data });
  }

  async listInspections(params: {
    schoolId?: number | string;
    result?: InspectResult;
    start?: string;
    end?: string;
    page?: number | string;
    pageSize?: number | string;
  }) {
    const p = Math.max(1, parseInt(String(params.page ?? 1), 10) || 1);
    const ps = Math.max(1, parseInt(String(params.pageSize ?? 20), 10) || 20);
    const sidInput = params.schoolId;
    const sidNum = sidInput !== undefined && sidInput !== null && String(sidInput).trim() !== '' ? Number(sidInput) : NaN;
    const sid = Number.isFinite(sidNum) && Number.isInteger(sidNum) ? sidNum : 1;
    return this.repo.listInspections({
      schoolId: sid,
      result: params.result,
      start: params.start,
      end: params.end,
      page: p,
      pageSize: ps,
    });
  }

  async createInspection(body: {
    schoolId?: number | string;
    date?: string;
    result: InspectResult;
    by: string;
    remark?: string;
  }) {
    if (!body?.result) throw new BadRequestException('result is required');
    if (!body?.by || String(body.by).trim() === '') throw new BadRequestException('by is required');
    const sidNum = body.schoolId !== undefined && body.schoolId !== null && String(body.schoolId).trim() !== '' ? Number(body.schoolId) : NaN;
    const schoolId = Number.isFinite(sidNum) && Number.isInteger(sidNum) ? sidNum : 1;
    const date = body.date || this.nowIso();
    const insertId = await this.repo.insertInspection({ schoolId, date, result: body.result, by: body.by, remark: body.remark });
    const rec: HygieneInspection = { id: insertId, schoolId, date, result: body.result, by: body.by, remark: body.remark };
    this.emit('hygiene-created', rec);
    return rec;
  }

  async listAssets(params: {
    schoolId?: number | string;
    asset?: string;
    start?: string;
    end?: string;
    page?: number | string;
    pageSize?: number | string;
  }) {
    const p = Math.max(1, parseInt(String(params.page ?? 1), 10) || 1);
    const ps = Math.max(1, parseInt(String(params.pageSize ?? 20), 10) || 20);
    const sidInput = params.schoolId;
    const sidNum = sidInput !== undefined && sidInput !== null && String(sidInput).trim() !== '' ? Number(sidInput) : NaN;
    const sid = Number.isFinite(sidNum) && Number.isInteger(sidNum) ? sidNum : 1;
    return this.repo.listAssets({
      schoolId: sid,
      asset: params.asset,
      start: params.start,
      end: params.end,
      page: p,
      pageSize: ps,
    });
  }

  async createAsset(body: {
    schoolId?: number | string;
    asset: string;
    date?: string;
    action: string;
    by: string;
  }) {
    if (!body?.asset || String(body.asset).trim() === '')
      throw new BadRequestException('asset is required');
    if (!body?.action || String(body.action).trim() === '')
      throw new BadRequestException('action is required');
    if (!body?.by || String(body.by).trim() === '') throw new BadRequestException('by is required');
    const sidNum = body.schoolId !== undefined && body.schoolId !== null && String(body.schoolId).trim() !== '' ? Number(body.schoolId) : NaN;
    const schoolId = Number.isFinite(sidNum) && Number.isInteger(sidNum) ? sidNum : 1;
    const date = body.date || this.nowIso();
    const insertId = await this.repo.insertAsset({ schoolId, asset: body.asset, date, action: body.action, by: body.by });
    const rec: AssetMaintenance = { id: insertId, schoolId, asset: body.asset, date, action: body.action, by: body.by };
    this.emit('asset-created', rec);
    return rec;
  }

  stream(): Observable<MessageEvent> {
    setTimeout(() => this.events$.next({ type: 'hello', data: { ok: true } }), 0);
    return this.events$.asObservable();
  }

  private seed() {}
}
