openapi: 3.0.3
info:
  title: Food Safety Platform (Minimal)
  version: 0.1.0
servers:
  - url: http://localhost:3000
    description: API Gateway
  - url: http://localhost:3101
    description: User Service
paths:
  /health:
    get:
      summary: Health check for API Gateway
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  service:
                    type: string
                  time:
                    type: string
                    format: date-time
  /users:
    get:
      summary: List users (User Service)
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PublicUser'
components:
  schemas:
    PublicUser:
      type: object
      required: [id, username, displayName]
      properties:
        id:
          type: string
        username:
          type: string
        displayName:
          type: string
