import { Controller, Get, Res, Query } from '@nestjs/common';
// 使用 any 避免本地缺少 @types/express 造成编译失败

@Controller('reg/reports')
export class ReportsController {
  @Get('export')
  export(
    @Query('format') format = 'csv',
    @Res()
    res: { setHeader: (k: string, v: string) => void; send: (b: unknown) => unknown },
  ) {
    const rows = [
      { name: '晨检', count: 220 },
      { name: '留样', count: 150 },
      { name: '消毒', count: 240 },
      { name: '陪餐', count: 90 },
      { name: '废弃物', count: 260 },
      { name: 'AI 预警', count: 45 },
    ];
    if (format === 'pdf') {
      // 简单 PDF 占位：实际应使用模板渲染
      const content = Buffer.from(`%PDF-1.4
% Simple placeholder PDF generated by API Gateway`);
      res.setHeader('Content-Type', 'application/pdf');
      res.setHeader('Content-Disposition', 'attachment; filename="daily-report.pdf"');
      return res.send(content);
    }
    // CSV 导出
    const header = '类别,数量' + '\n';
    const body = rows.map((r) => `${r.name},${r.count}`).join('\n');
    const csv = '﻿' + header + body;
    res.setHeader('Content-Type', 'text/csv; charset=utf-8');
    res.setHeader('Content-Disposition', 'attachment; filename="daily-report.csv"');
    return res.send(csv);
  }
}
